apiVersion: v1
kind: Service
metadata:
  name: world-cup-contest-loadbalancer-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080 
    targetPort: 8080
    protocol: TCP
  selector:
    app: world-cup-contest