apiVersion: v1
kind: Service
metadata:
  name: world-cup-contest-backend-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8090 
    targetPort: 8090
    protocol: TCP
  selector:
    app: world-cup-contest