apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-cup-contest-deployment
  labels:
    test: world-cup-contest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: world-cup-contest
  template:
    metadata:
      labels: 
        app: world-cup-contest
    spec: 
      containers:
      - name: world-cup-contest
        image: tonyqui/k8s-frontend:1.1
        ports:
          - containerPort: 8090
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 8090
            httpHeaders:
            - name: LIVENESS-PROBE
              value: READY
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthCheck
            port: 8090
            httpHeaders:
            - name: READINESS-PROBE
              value: READY
          initialDelaySeconds: 3
          periodSeconds: 3
