apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: world_cup_contest_deployment
spec:
  replicas: 2
  template: 
    labels: 
      app: world_cup_contest
    spec: 
      containers:
      - name: world_cup_contest
        image: tonyqui/k8s-demo:1.0
        ports:
          - containerPort: 8080
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 8080
            httpHeaders:
            - name: LIVENESS-PROBE
              value: READY
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthCheck
            port: 8080
            httpHeaders:
            - name: READINESS-PROBE
              value: READY
          initialDelaySeconds: 3
          periodSeconds: 3