apiVersion: v1
kind: Pod
metadata:
  name: world-cup-contest
  labels:
    app: world-cup-contest
spec:
  containers:
  - name: world-cup-contest
    image: tonyqui/k8s-demo:1.0
    ports:
      - containerPort: 8080
    livenessProbe:
      failureThreshold: 1
      httpGet:
        path: /livenessProbe
        port: 8080
        httpHeaders:
        - name: LIVENESS-PROBE
          value: READY
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      failureThreshold: 1
      httpGet:
        path: /healthCheck
        port: 8080
        httpHeaders:
        - name: READINESS-PROBE
          value: READY
      initialDelaySeconds: 3
      periodSeconds: 3
    